### ISSUE TITLE
Error model creation crash

### ISSUE THREAD

**Issue by yoann-dufresne** [HadrienG/InSilicoSeq#103]
I'm trying to use iss to create a matagenomic sample with perfect reads (no error).
If I understand well the command line, it's not directly possible to specify 0% of error.

So I tried to create a model on simulated reads without any errors.
But the execution stopped on the following error :
```bash
INFO:iss.app:Starting iss model
INFO:iss.app:Using KDE ErrorModel
INFO:iss.bam:Reading bam file: reads.bam
INFO:iss.bam:Calculating insert size distribution
INFO:iss.bam:Calculating mean and base quality distribution
Traceback (most recent call last):
  File "/home/yoann/Softwares/Anaconda/bin/iss", line 10, in <module>
    sys.exit(main())
  File "/home/yoann/Softwares/Anaconda/lib/python3.6/site-packages/iss/app.py", line 489, in main
    args.func(args)
  File "/home/yoann/Softwares/Anaconda/lib/python3.6/site-packages/iss/app.py", line 263, in model_from_bam
    bam.to_model(args.bam, args.output)
  File "/home/yoann/Softwares/Anaconda/lib/python3.6/site-packages/iss/bam.py", line 205, in to_model
    length_forward = min((len(x) for x in hists_f if len(x) > 1))
ValueError: min() arg is an empty sequence
```

Do you have any idea of the mistake that I made ?

**Comment by HadrienG** [comment]
Hi!

I don't think you made any mistakes:

I'm assuming that in your bam files all your reads have the same, very high quality (Q50? 60?).
As a result there will be mostly empty bins in the histogram of read qualities, which will crash somewhere as I didn't plan for this edge-case.

Could you share your bam file and a bit more information about your inout data (Seq technology, read length, paired/single) so I can debug further?

Otherwise I could add an option for generating perfect reads, it wouldn't be a big change in the codebase. But are you sure the basic model does not fit your needs? It's Q30 all the way and only substitutions errors (no indels).

**Comment by yoann-dufresne** [comment]
Yes it's because the read qualities are all the 'I' value.

I'm trying to test some error correctors on synthetic metagenomic data.
So, to evaluate their quality, I have to know the truth (ie the exact read before any insertion).

For that, I would like to generate a a synthetic metagenomic dataset without any error and from this dataset, generate an erroneous one.

**Comment by HadrienG** [comment]
Even if I fixed the modelling code to work with uniform read qualities, `I` is still only Q40 in Illumina 1.8 encoding, which `InSilicoSeq` would rightly interpret at 99.99% accuracy, so you'd still get reads with errors at the read generation stage.

That said I believe it's a good use case, and if you're willing to wait a few days on this, I'll add a `perfect` error model option that you can pass to `--model` during `iss generate`.

**Comment by yoann-dufresne** [comment]
Thanks for the future improvements :)

**Comment by HadrienG** [comment]
You should now be able to use `--mode perfect` in version `1.4.0`
