### ISSUE TITLE
HiSeq reads length

### ISSUE THREAD

**Issue by gregoruar** [HadrienG/InSilicoSeq#175]
Hi Hadrien! During the experiment I figured out that with HiSeq platform length of reads equals to 126 bp as opposed to 125 bp stated in tutorial. Could you clarify me this issue?

**Comment by HadrienG** [comment]
Hi! 

This is true for all error models in InSilicoSeq (i.e. MiSeq will produce 301bp reads). Typically on an Illumina instruments you'll do _n+1_ cycles for a _n_bp run. The _n+1_ base can be considered an artefact of Illumina sequencing; some sequencing centres drop the extra base at the demultiplexing step, some don't. 

I'd advise to always remove it at QC, since it usually has a terrible error rate (even if the basecalling tells you otherwise)
