### ISSUE TITLE
add iss download command

### ISSUE THREAD

**Issue by jhayer** [HadrienG/InSilicoSeq#39]
The idea would be to have a specific command for downloading genomes from NCBI

**Comment by HadrienG** [comment]
It sound like a good idea, but I'm reluctant to implement it now since the `--ncbi` option is rather slow (especially for viruses and archaea) and should not be the preferred way of running InSilicoSeq at the moment. 

I'm inclined to put this on hold while I haven't found a more efficient way to download random genomes. As it is now the functionality is not good enough to warrant its own subcommand.

**Comment by HadrienG** [comment]
@jhayer I've sped up the ncbi downloads. Do you still think it is a good idea?
What would be your use case for this?

**Comment by jhayer** [comment]
Yes I would use it to make simulated viral metagenomics datasets from random viruses. So I do not spend time choosing and collecting genomes. Great that you managed to speed up the dl :-)

**Comment by HadrienG** [comment]
I'm closing this per our phone discussion, since `iss generate --ncbi` downloads and save the downloaded genomes already
