### ISSUE TITLE
Errors when running code

### ISSUE THREAD

**Issue by AShaw1802** [HadrienG/InSilicoSeq#45]
Hi,
I've been trying to use InSiclicoSeq to create an NGS dataset from a single 7.4kb genome (starting with a shortened fragment), running the program from the linux command line in a qiime VirtualBox. I've been given a couple of error messages however; the first (error message 1 attached) stating invalid syntax in app.py at line 78. I could avoid this by removing the "elif" segment that deals with ncbi genomes (lines 68-78), but then run into another issue later where InSilicoSeq calls seq.py (error message 2 attached), this time a type error. 
I've also attached the DNA sequence I was using in my command- iss generate --genomes PV3_gb_MF678293Short.fasta -model miseq --output miseq_reads -n 10000

[Error1.txt](https://github.com/HadrienG/InSilicoSeq/files/1660436/Error1.txt)
[Error2.txt](https://github.com/HadrienG/InSilicoSeq/files/1660437/Error2.txt)
[PV3_gb_MF678293Short.txt](https://github.com/HadrienG/InSilicoSeq/files/1660455/PV3_gb_MF678293Short.txt)

I can provide further information if it helps to recreate the errors. And thanks for creating this software by the way- I've spent days trying to find an up to date package for NGS data simulation.
Thanks,
Alex

**Comment by HadrienG** [comment]
Hi,

Thanks for reporting these! The first error is due to ` for g, n in zip(*args.ncbi, *args.n_genomes):` being python3 only syntax.

`InSilicoSeq` is developed in python3 and supposed to be backwards compatible with python2 but sometimes python3 only syntax slips through the cracks.  

In your second error, the problem is that the insert size modelling tried to generate a template that is bigger than your input sequence.


I will try to publish a minor release fixing those two bugs as soon as possible.

Thanks for your interest in `InSilicoSeq`!

Best,
Hadrien

**Comment by AShaw1802** [comment]
Hi Hadrien,

Thanks very much for publishing the fixes and for the python3 note- I’ll give it a try again shortly.
Cheers,

Alex

**Comment by HadrienG** [comment]
No problem!

I just published a minor bugfix release, you should be able to install it with `pip install --upgrade insilicoseq`

Best,
Hadrien
